server:
  port: 8888

jasypt:
   encryptor:
     algorithm: PBEWithMD5AndDES
     password: InnerEval

spring:
  datasource:
    url: jdbc:mysql://172.30.3.112:3306/innereval?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(GkHBdBnx4f/TWbEfb1ziN+iVyBiLtxgp)
    password: ENC(LHH2bgrCKyUCGvVmIsrrPQ==)
  redis:
    host: 172.30.3.144
    port: 6379
    password: my_redis
    database: 1
    pool:
      max-idle: 300
      max-active: 600
      max-wait: 1000




